#version: "3.8"

services:
  frontend:
    container_name: frondend
    image: nginx:alpine

    ports:
      - 80:80
      - 443:443

    volumes:
      - /home/tamim/project/idm-demo/surve/nginx/public:/usr/share/nginx/html
    
    
    depends_on:
      - api
      - db

    networks:
      - frontend

    command: nginx -g 'daemon off;'


  
  api:

    container_name: api-app
    build:
      context: ./surve/api
      dockerfile: Dockerfile

    ports:
      - 5000:8000

    networks: 
        - backend
        - frontend

    environment:
      - DB_HOST=db
      - DB_USER=survey_user
      - DB_PASS=userpass
      - DB_NAME=survey_db


    working_dir: /app
    depends_on:
        - db
    volumes:
        - ./survey/api:/app

    healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
        interval: 30s
        timeout: 10s
        retries: 5
  
  db:
    container_name: db
    image: mysql:5.7
    restart: unless-stopped

    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: survey_db
      MYSQL_USER: survey_user
      MYSQL_PASSWORD: userpass
      # Optional your original vars:
      # DB_HOST: db
      # DB_USER: survey_user
      # DB_PASS: userpass
      # DB_NAME: survey_db
    ports:
      - "3306:3306"
    volumes:
      - ./idm-demo/surve/mysql:/var/lib/mysql
    networks:
      - backend

  idm:
    container_name: idm
    
    build:
      context: .
      dockerfile: Dockerfile

    networks:
        - frontend

    command: python app.py

  
networks:
  frontend:
    driver: bridge

  backend:
    driver: bridge

#------Voulumes------
volumes:
  api:
  backend:


