version: '3.8'

services:
  web:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - frontend:/usr/share/nginx/html
    working_dir: /web
    networks:
      - survey-fontend

    restart: always

  api:
    build: ./api
    volumes:
      - backend:/var/www/html
    
    working_dir: /api
    
    networks:
      - survey-backend
      - survey-fontend
    restart: always
    environment:
      - DB_HOST=db
      - DB_USER=survey_user
      - DB_PASS=userpass
      - DB_NAME=survey_db

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: survey_db
      MYSQL_USER: survey_user
      MYSQL_PASSWORD: userpass
    volumes:
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
      - mysdql:/mysql2
    working_dir: /mysql2
    
    networks:
      - survey-backend
    restart: always

networks:
  survey-fontend:
    driver: bridge
    internal: false

  survey-backend:
    driver: bridge
    internal: true


volumes:
  frontend:
  backend:
  mysdql: